//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

//using System;
//using System.Data.Entity;
//using System.Data.Entity.Infrastructure;

//public partial class MunicipalidadEntidad : DbContext
//{
//    public MunicipalidadEntidad()
//        : base("name=MunicipalidadEntidad")
//    {
//    }

//    protected override void OnModelCreating(DbModelBuilder modelBuilder)
//    {
//        throw new UnintentionalCodeFirstException();
//    }

//    public virtual DbSet<Actividades> Actividades { get; set; }
//    public virtual DbSet<Inscripciones> Inscripciones { get; set; }
//    public virtual DbSet<tipoActividades> tipoActividades { get; set; }
//    public virtual DbSet<Usuario> Usuario { get; set; }
//    public virtual DbSet<Noticias> Noticias { get; set; }
//    public virtual DbSet<Sugerencias> Sugerencias { get; set; }
//}
